@HostAddress = http://localhost:5286
@AdPostId = 79db479b-86f8-4076-8744-e7623a860056

### Get all ad posts
GET {{HostAddress}}/api/AdPosts
Accept: application/json

### Get ad post by id
GET {{HostAddress}}/api/AdPosts/{{AdPostId}}
Accept: application/json

### Create ad post
POST {{HostAddress}}/api/AdPosts
Content-Type: application/json

{
  "userId": "998eb93b-e028-4ae8-9673-3483484cf3df",
  "title": "Велосипед",
  "price": 5000
}

### Update ad post
PUT {{HostAddress}}/api/AdPosts/{{AdPostId}}
Content-Type: application/json

{
  "adPostId": "79db479b-86f8-4076-8744-e7623a860056",
  "title": "Мотоцикл",
  "description": "Мотоцикл Suzuki 2018 г.",
  "price": 40000
}

### Delete ad post
DELETE {{HostAddress}}/api/AdPosts/{{AdPostId}}