@HostAddress = http://localhost:5286
@UserId = 958c0326-239c-497a-a3ce-cdb27245bd54

### Get user by id
GET {{HostAddress}}/api/Users/{{UserId}}
Accept: application/json

### Register new user
POST {{HostAddress}}/api/Users/Register
Content-Type: application/json

{
  "email": "petrpetrov@mail.ru",
  "firstName": "Петр",
  "lastName": "Петров",
  "password": "abc12345"
}